### PR TITLE
fix: Daily snapshot automatic recovery

### LINKED ISSUE #93: Daily snapshot automatic recovery
**Issue summary**

It happened and may happen again that Forest is just unable to go past a certain epoch. Be it a lack of state migration (or an incorrect one) or another issue within Forest, the daily snapshot should continue working without manual intervention.

A general idea is as follows - if the snapshot was not generated in X hours, fetch the FilOps snapshot, import it to Forest and then generate our own snapshot. X could be 30, but let's ensure it's easily configurable.

A proper notification should be sent to Slack when that happens.

**Other information and links**

### PR DESCRIPTION
**Pull request by samuelarogbonlo**
**Summary of changes**
Changes introduced in this pull request:
- if the daily snapshot was not generated in 24 hours, fetch the FilOps snapshot, then upload it to forest-snapshot bucket.

**Reference issue to close (if applicable)**

Closes #93 

**Other information and links**

### CODE REVIEW

File: daily_snapshot_terraform/modules/daily_snapshot/service/upload_filops_snapshot.sh [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+CURRENT_TIMESTAMP=$(date -u -d "$(date -u +%Y-%m-%d)" +%s)
+
+# Difference in timestamps, in days
+DIFF=$(( (CURRENT_TIMESTAMP - SNAPSHOT_TIMESTAMP) / 86400 ))
+
+# Function to send Slack alert
+send_slack_alert() {
+    local message="$1"
+    curl -X POST -H 'Content-type: application/json' -H "Authorization: Bearer $SLACK_API_TOKEN" \
+    --data "{\"channel\":\"#forest-dump\",\"text\":\"${message}\"}" \
```
Comment (lemmih) [inline daily_snapshot_terraform/modules/daily_snapshot/service/upload_filops_snapshot.sh:31]:
```suggestion
    --data "{\"channel\":\"#forest-notifications\",\"text\":\"${message}\"}" \
```

File: daily_snapshot_terraform/modules/daily_snapshot/service/upload_filops_snapshot.sh [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+}
+
+COMMANDS=$(cat << HEREDOC
+set -eux
+cat << EOF > "config.toml"
+[client]
+data_dir = "/home/forest/forest_db"
+encrypt_keystore = false
+EOF
+forest --config config.toml --chain "$CHAIN" --detach
```
Comment (lemmih) [inline daily_snapshot_terraform/modules/daily_snapshot/service/upload_filops_snapshot.sh:42]: You don't want to run the forest node.

**Review by lemmih — CHANGES_REQUESTED** [review]
Looks good! Minor fixes and it's good to go.

File: daily_snapshot_terraform/modules/daily_snapshot/service/upload_filops_snapshot.sh (hunk 2 above)
Comment (lemmih) [reply daily_snapshot_terraform/modules/daily_snapshot/service/upload_filops_snapshot.sh:42]: `--chain "$CHAIN"`

Comment (lemmih) [reply daily_snapshot_terraform/modules/daily_snapshot/service/upload_filops_snapshot.sh:42]: You just need to run `forest-cli --chain $CHAIN snapshot fetch --vendor filops`

Comment (lemmih) [reply daily_snapshot_terraform/modules/daily_snapshot/service/upload_filops_snapshot.sh:42]: We do not. Note that you should not use any configuration here.

**Review by lemmih — APPROVED** [review]
