### PR TITLE
fix: daily snapshot and snapshot script inconsistency

### LINKED ISSUE #213: Fix inconsistency in scripts for sync check and snapshot service
**Issue summary**

After a detailed review and comprehensive testing of the recently merged updates, I've identified a discrepancy: the script exhibits inconsistent behavior when executed through our Terraform setup versus when it's run manually.

What's the discrepancy? Encountering this kind of bug while running the sync check and snapshot service is a possibility, although it doesn't occur frequently. The bug is discussed in more detail in this Digital Ocean Community [forum](https://www.digitalocean.com/community/questions/cannot-get-updates-ubuntu-20-04) and also in related [Github issues](https://github.com/digitalocean/droplet-agent/issues/34).

```
root@sam-forest-sync-check:~# cat init_log.txt
+ apt-get update
Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Hit:2 https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease
Hit:3 http://mirrors.digitalocean.com/ubuntu jammy InRelease
Get:4 http://mirrors.digitalocean.com/ubuntu jammy-updates InRelease [119 kB]
Get:5 https://download.docker.com/linux/ubuntu jammy InRelease [48.9 kB]
Err:2 https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 35696F43FC7DB4C2
Get:6 http://mirrors.digitalocean.com/ubuntu jammy-backports InRelease [109 kB]
Get:7 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [661 kB]
Get:8 http://security.ubuntu.com/ubuntu jammy-security/main Translation-en [153 kB]
Get:9 http://security.ubuntu.com/ubuntu jammy-security/main amd64 c-n-f Metadata [11.2 kB]
Get:10 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [667 kB]
Get:11 http://security.ubuntu.com/ubuntu jammy-security/restricted Translation-en [106 kB]
Get:12 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 c-n-f Metadata [536 B]
Get:13 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [770 kB]
Get:14 http://security.ubuntu.com/ubuntu jammy-security/universe Translation-en [140 kB]
Get:15 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 c-n-f Metadata [16.4 kB]
Get:16 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [36.5 kB]
Get:17 http://security.ubuntu.com/ubuntu jammy-security/multiverse Translation-en [7060 B]
Get:18 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 c-n-f Metadata [260 B]
Get:19 https://download.docker.com/linux/ubuntu jammy/stable amd64 Packages [21.4 kB]
Get:20 http://mirrors.digitalocean.com/ubuntu jammy-updates/main amd64 Packages [873 kB]
Get:21 http://mirrors.digitalocean.com/ubuntu jammy-updates/main Translation-en [212 kB]
Get:22 http://mirrors.digitalocean.com/ubuntu jammy-updates/main amd64 c-n-f Metadata [15.6 kB]
Get:23 http://mirrors.digitalocean.com/ubuntu jammy-updates/restricted amd64 Packages [678 kB]
Get:24 http://mirrors.digitalocean.com/ubuntu jammy-updates/restricted Translation-en [108 kB]
Get:25 http://mirrors.digitalocean.com/ubuntu jammy-updates/restricted amd64 c-n-f Metadata [536 B]
Get:26 http://mirrors.digitalocean.com/ubuntu jammy-updates/universe amd64 Packages [965 kB]
Get:27 http://mirrors.digitalocean.com/ubuntu jammy-updates/universe Translation-en [210 kB]
Get:28 http://mirrors.digitalocean.com/ubuntu jammy-updates/universe amd64 c-n-f Metadata [21.5 kB]
Get:29 http://mirrors.digitalocean.com/ubuntu jammy-updates/multiverse amd64 Packages [41.6 kB]
Get:30 http://mirrors.digitalocean.com/ubuntu jammy-updates/multiverse Translation-en [9768 B]
Get:31 http://mirrors.digitalocean.com/ubuntu jammy-updates/multiverse amd64 c-n-f Metadata [476 B]
Get:32 http://mirrors.digitalocean.com/ubuntu jammy-backports/main amd64 Packages [40.8 kB]
Get:33 http://mirrors.digitalocean.com/ubuntu jammy-backports/main amd64 c-n-f Metadata [388 B]
Get:34 http://mirrors.digitalocean.com/ubuntu jammy-backports/universe amd64 Packages [22.3 kB]
Get:35 http://mirrors.digitalocean.com/ubuntu jammy-backports/universe Translation-en [15.4 kB]
Get:36 http://mirrors.digitalocean.com/ubuntu jammy-backports/universe amd64 c-n-f Metadata [576 B]
Fetched 6191 kB in 7s (848 kB/s)
Reading package lists...
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 35696F43FC7DB4C2
W: https://download.docker.com/linux/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: Failed to fetch https://repos-droplet.digitalocean.com/apt/droplet-agent/dists/main/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 35696F43FC7DB4C2
W: Some index files failed to download. They have been ignored, or old ones used instead.
+ apt-get install -y ruby ruby-dev gcc make
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 2299 (apt-get)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
```

**Other information and links**

### PR DESCRIPTION
**Pull request by samuelarogbonlo**
**Summary of changes**
Changes introduced in this pull request:
- fix daily snapshot and snapshot script inconsistency

**Reference issue to close (if applicable)**

Closes 
#213

**Other information and links**

### CODE REVIEW

File: terraform/modules/daily_snapshot/service/init.sh [hunk 1]
```diff
@@ -1,13 +1,13 @@
 #!/bin/bash
 
-set -eux 
+set -eux
 
 # Use APT specific mechanism to ensure non-interactive operation and wait for the lock
-sudo DEBIAN_FRONTEND=noninteractive apt-get -qqq --yes -o DPkg::Lock::Timeout=-1 update
-sudo DEBIAN_FRONTEND=noninteractive apt-get -qqq --yes -o DPkg::Lock::Timeout=-1 install -y ruby ruby-dev s3cmd anacron awscli
+sudo DEBIAN_FRONTEND=noninteractive  apt-get -qqq --yes -o DPkg::Lock::Timeout=30 update
+sudo DEBIAN_FRONTEND=noninteractive  apt-get -qqq --yes -o DPkg::Lock::Timeout=30 install -y ruby ruby-dev s3cmd anacron awscli
```
Comment (lemmih) [inline terraform/modules/daily_snapshot/service/init.sh:7]: Btw, why do we use `sudo` here?

```suggestion
sudo DEBIAN_FRONTEND=noninteractive apt-get -qqq --yes -o DPkg::Lock::Timeout=30 update
sudo DEBIAN_FRONTEND=noninteractive apt-get -qqq --yes -o DPkg::Lock::Timeout=30 install -y ruby ruby-dev s3cmd anacron awscli
```

**Review by lemmih — APPROVED** [review]

File: terraform/modules/daily_snapshot/service/init.sh [hunk 2]
```diff
@@ -1,13 +1,13 @@
 #!/bin/bash
 
-set -eux 
+set -eux
 
 # Use APT specific mechanism to ensure non-interactive operation and wait for the lock
-sudo DEBIAN_FRONTEND=noninteractive apt-get -qqq --yes -o DPkg::Lock::Timeout=-1 update
-sudo DEBIAN_FRONTEND=noninteractive apt-get -qqq --yes -o DPkg::Lock::Timeout=-1 install -y ruby ruby-dev s3cmd anacron awscli
+DEBIAN_FRONTEND=noninteractive apt-get -qqq --yes -o DPkg::Lock::Timeout=30 update
+DEBIAN_FRONTEND=noninteractive apt-get -qqq --yes -o DPkg::Lock::Timeout=30 install -y ruby ruby-dev s3cmd anacron awscli
```
Comment (aatifsyed) [inline terraform/modules/daily_snapshot/service/init.sh:8]: nonblocking: you can just have one `DEBIAN_FRONTEND=noninteractive` higher up (with a comment), and use bare `apt` operations

File: terraform/modules/sync_check/service/init.sh [hunk 3]
```diff
@@ -30,8 +29,8 @@ metrics_nfs_sample_rate: 600
 container_cache_metadata_limit: 600
 disable_zero_mem_process_filter: true
 disable_all_plugins: true
-disable_cloud_metadata: true 
-ignore_system_proxy: true 
+disable_cloud_metadata: true
+ignore_system_proxy: true
```
Comment (aatifsyed) [inline terraform/modules/sync_check/service/init.sh:33]: nonblocking: you can add a formatter to ensure there's no trailing whitespace so changes like these aren't needed

**Review by aatifsyed — APPROVED** [review]
