### PR TITLE
fix: prune logs older than 2 weeks

### LINKED ISSUE #367: Snapshot service log rotation
**Issue summary**

A potential cause for an outage of the snapshot service is amassing too many logs. 

```
root@forest-snapshot:~# uptime
 14:03:15 up 21 days, 46 min,  1 user,  load average: 0.13, 0.88, 1.94
root@forest-snapshot:~# du -sh logs/
4.5G    logs/
```

While this is not critical (we've got some slack when it comes to disk space, and we update the service often enough, e.g., for the network upgrades), it'd be nice to have it bounded to, e.g., 5 GiB, two last weeks or something along those lines.

**Other information and links**

### PR DESCRIPTION
**Pull request by samuelarogbonlo**
**Summary of changes**
Changes introduced in this pull request:
- Prune logs older than 2 weeks

**Reference issue to close (if applicable)**

Closes #367 

**Other information and links**

### CODE REVIEW

File: terraform/modules/daily_snapshot/service/daily_snapshot.rb [hunk 1]
```diff
@@ -63,6 +74,9 @@ def latest_snapshot_date(chain_name = 'calibnet')
   end
 end
 
+# Prune logs files(txt) in the logs directory older than 2 weeks
+prune_logs
+
```
Comment (LesnyRumcajs) [inline terraform/modules/daily_snapshot/service/daily_snapshot.rb:79]: Let's do it at the end of the file. If it fails for whatever reason, at least the rest of the script will finish.

Comment (samuelarogbonlo) [reply terraform/modules/daily_snapshot/service/daily_snapshot.rb]: @LesnyRumcajs done

**Review by LesnyRumcajs — APPROVED** [review]

**Review by jdjaustin — APPROVED** [review]
