### PR TITLE
Set-up NTP

### LINKED ISSUE #140: Set-up NTP on forest and lotus nodes
**Issue summary**

**Task summary**
forest calibnet  and lotus- mainnet nodes keep producing the same error 
```
2023-07-12T20:21:12.815084Z  INFO forest_filecoin::chain_sync::tipset_syncer: Validating tipset: EPOCH = 728897, N blocks = 1    
2023-07-12T20:21:12.815140Z  INFO forest_filecoin::chain_sync::tipset_syncer: Validating tipset: EPOCH = 728897, N blocks = 1    
2023-07-12T20:21:12.815150Z  WARN forest_filecoin::chain_sync::tipset_syncer: Validating block [CID = bafy2bzacebvv7goigk5fzn3nvrrixwdnjerv3nef44y6zwjtzcnsgegz5xon6] in EPOCH = 728897 failed: Block received from the future: now = 1689193272, block = 1689193290    
2023-07-12T20:21:12.815167Z  WARN forest_filecoin::chain_sync::tipset_syncer: Sync messages check state failed for single tipset    
2023-07-12T20:21:12.815173Z ERROR forest_filecoin::chain_sync::tipset_syncer: Syncing tipset range [728894, 728897] failed: Block received from the future: now = 1689193272, block = 1689193290
```

One way to to fix this is to install and enable `NTP` to synchronize the time differences 

**Other information and links**

### PR DESCRIPTION
**Pull request by samuelarogbonlo**
**Summary of changes**
Changes introduced in this pull request:
- Install and Enable NTP to synchronize the time differences

**Reference issue to close (if applicable)**

Closes #140 

**Other information and links**

### CODE REVIEW

File: terraform/modules/filecoin_node/lotus.sh [hunk 1]
```diff
@@ -26,6 +26,10 @@ if [ -f "/root/.ssh/authorized_keys" ]; then
   chmod 0600 "/home/${NEW_USER}/.ssh/authorized_keys"
 fi
 
+#install NTP to synchronize the time differences
+timedatectl set-ntp no
```
Comment (lemmih) [inline terraform/modules/filecoin_node/lotus.sh:30]: Why do we need to disable ntp here?

Comment (lemmih) [reply terraform/modules/filecoin_node/lotus.sh:30]: Okay. I don't see why that is necessary, but I trust you know what you're doing.

**Review by lemmih — APPROVED** [review]
