### PR TITLE
Use Latest tag for Lotus

### LINKED ISSUE #274: Benchmark script: Lotus db is not correctly destroyed
**Describe the bug**

Lotus db is sometimes not correctly cleaned between different benchmark runs. This might also be a potential explanation for #268.

**To Reproduce**
1. Configure correctly terraform to run the service on a test droplet
2. Launch the service and wait for a few days
3. See error

**Log output**

<details>
  <summary>Log Output</summary>

  ```
I, [2023-09-21T21:08:47.312984 #9]  INFO -- : $ ./lotus/lotus daemon --config /chainsafe/tmp/.lotus/lotus.toml --import-snapshot /chainsafe/tmp/933120_2023_09_21T18_13_00Z.car --halt-after-import
2023-09-21T21:08:47.380Z	INFO	main	lotus/daemon.go:228	lotus repo: /chainsafe/tmp/.lotus
2023-09-21T21:08:47.381Z	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-0170db1f394b35d995252228ee359194b13199d259380541dc529fb0099096b0.vk is ok
2023-09-21T21:08:47.382Z	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-0cfb4f178bbb71cf2ecfcd42accce558b27199ab4fb59cb78f2483fe21ef36d9.vk is ok
2023-09-21T21:08:47.382Z	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-3ea05428c9d11689f23529cde32fd30aabd50f7d2c93657c1d3650bca3e8ea9e.vk is ok
2023-09-21T21:08:47.382Z	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-5294475db5237a2e83c3e52fd6c2b03859a1831d45ed08c4f35dbf9a803165a9.vk is ok
2023-09-21T21:08:47.382Z	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-empty-sector-update-merkletree-poseidon_hasher-8-0-0-61fa69f38b9cc771ba27b670124714b4ea77fbeae05e377fb859c4a43b73a30c.vk is ok
2023-09-21T21:08:47.382Z	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-empty-sector-update-merkletree-poseidon_hasher-8-0-0-92180959e1918d26350b8e6cfe217bbdd0a2d8de51ebec269078b364b715ad63.vk is ok
2023-09-21T21:08:47.382Z	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-empty-sector-update-merkletree-poseidon_hasher-8-8-0-3b7f44a9362e3985369454947bc94022e118211e49fd672d52bec1cbfd599d18.vk is ok
2023-09-21T21:08:47.382Z	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-2-b62098629d07946e9028127e70295ed996fe3ed25b0f9f88eb610a0ab4385a3c.vk is ok
2023-09-21T21:08:47.382Z	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-50c7368dea9593ed0989e70974d28024efa9d156d585b7eea1be22b2e753f331.vk is ok
2023-09-21T21:08:47.382Z	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-7d739b8cf60f1b0709eeebee7730e297683552e4b69cab6984ec0285663c5781.vk is ok
2023-09-21T21:08:47.382Z	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-559e581f022bb4e4ec6e719e563bf0e026ad6de42e56c18714a2c692b1b88d7e.vk is ok
2023-09-21T21:08:47.382Z	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-stacked-proof-of-replication-merkletree-poseidon_hasher-8-8-0-sha256_hasher-82a357d2f2ca81dc61bb45f4a762807aedee1b0a53fd6c4e77b46a01bfef7820.vk is ok
2023-09-21T21:08:47.383Z	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-stacked-proof-of-replication-merkletree-poseidon_hasher-8-8-2-sha256_hasher-96f1b4a04c5c51e4759bbf224bbc2ef5a42c7100f16ec0637123f16a845ddfb2.vk is ok
2023-09-21T21:08:47.383Z	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-empty-sector-update-merkletree-poseidon_hasher-8-0-0-fb9e095bebdd77511c0269b967b4d87ba8b8a525edaa0e165de23ba454510194.vk is ok
2023-09-21T21:08:47.386Z	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-2-2627e4006b67f99cef990c0a47d5426cb7ab0a0ad58fc1061547bf2d28b09def.vk is ok
2023-09-21T21:08:47.386Z	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-empty-sector-update-merkletree-poseidon_hasher-8-8-2-102e1444a7e9a97ebf1e3d6855dcc77e66c011ea66f936d9b2c508f87f2f83a7.vk is ok
2023-09-21T21:08:47.386Z	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-stacked-proof-of-replication-merkletree-poseidon_hasher-8-0-0-sha256_hasher-6babf46ce344ae495d558e7770a585b2382d54f225af8ed0397b8be7c3fcd472.vk is ok
2023-09-21T21:08:47.386Z	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-stacked-proof-of-replication-merkletree-poseidon_hasher-8-0-0-sha256_hasher-032d3138d22506ec0082ed72b2dcba18df18477904e35bafee82b3793b06832f.vk is ok
2023-09-21T21:08:47.387Z	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-stacked-proof-of-replication-merkletree-poseidon_hasher-8-0-0-sha256_hasher-ecd683648512ab1765faa2a5f14bab48f676e633467f0aa8aad4b55dcb0652bb.vk is ok
2023-09-21T21:08:47.387Z	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-0377ded656c6f524f1618760bffe4e0a1c51d5a70c4509eedae8a27555733edc.vk is ok
2023-09-21T21:08:47.777Z	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-fil-inner-product-v1.srs is ok
2023-09-21T21:08:47.777Z	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:233	parameter and key-fetching complete
ERROR: reading user input: EOF

Importing chain or snapshot will by default delete existing local chain data. Do you want to proceed and delete? (yes/no): E, [2023-09-21T21:08:47.830919 #9] ERROR -- : Fiasco during benchmark run. Deleting downloaded files, cleaning DB and stopping process...
  ```
</details>

**Expected behaviour**

We should be able to run the service continuously.

We should also correctly report any errors, this not seem to be the case here (for instance, `Benchmark finished` is not shown in report).

**Other information and links**

### PR DESCRIPTION
**Pull request by elmattic**
**Summary of changes**
Changes introduced in this pull request:
- Use a fixed tag for Lotus to avoid any _surprises_
- Try add monitoring like we do for other services (sync check, snapshot export)

**Reference issue to close (if applicable)**

Closes #274

**Other information and links**

We will start with [v1.23.3](https://github.com/filecoin-project/lotus/releases/tag/v1.23.3) and update it manually from time to time (so we can make sure nothing breaks, i.e. change in cli args).

### CODE REVIEW

File: terraform/modules/benchmark/service/lotus_bench.rb [hunk 1]
```diff
@@ -41,11 +41,7 @@ def clone_command
   end
 
   def checkout_command
-    if @chain == 'mainnet'
-      exec_command(%w[git checkout releases])
-    else
-      exec_command(%w[git checkout master])
-    end
+    exec_command(%w[git checkout release/v1.23.3])
```
Comment (LesnyRumcajs) [inline terraform/modules/benchmark/service/lotus_bench.rb:44]: I think such thing would be nicer to have in terraform variables (with `v1.23.3` as default)

Comment (elmattic) [reply terraform/modules/benchmark/service/lotus_bench.rb:44]: Good idea, will move it out!

Comment (elmattic) [reply terraform/modules/benchmark/service/lotus_bench.rb]: Done.

**Review by LesnyRumcajs — APPROVED** [review]
