### PR TITLE
fix daily snapshot convoluted and bloated logs

### LINKED ISSUE #321: Daily snapshot process logs are convoluted and bloated
**Issue summary**

The `_script_run` logs are displayed weirdly. Metrics are part of the `_script_run` log (line by line, separated by commands), which is unhelpful given that there is a separate metrics file.
```
...
+ echo '2023-10-21 15:21:17 peer_tipset_epoch{PEER="12D3KooWQUH9UbPc2BUBKw5EMrrvYxTBkbYDKi3Be5UdnMXgYf8u"} -1'
+ IFS=
+ read -r line
++ date '+%Y-%m-%d %H:%M:%S'
+ echo '2023-10-21 15:21:17 peer_tipset_epoch{PEER="12D3KooWQUn93ou1Wy2USK2BHRRJmyR6aQxwwya89NU7p75bGTEH"} -1'
+ IFS=
+ read -r line
++ date '+%Y-%m-%d %H:%M:%S'
+ echo '2023-10-21 15:21:17 peer_tipset_epoch{PEER="12D3KooWQVy9g4snnHNfRtR1NepM4KtcSrN87mJSVFHJopZV2QR1"} -1'
+ IFS=
+ read -r line
++ date '+%Y-%m-%d %H:%M:%S'
...
```

The logs also end up being huge:
```
172K    mainnet_2023-10-21T14_25_30_daemon.txt
45M     mainnet_2023-10-21T14_25_30_metrics.txt
73M     mainnet_2023-10-21T14_25_30_script_run.txt
```

Cleanup the daemon logs and reduce the amount of metrics collected.

**Other information and links**

### PR DESCRIPTION
**Pull request by samuelarogbonlo**
**Summary of changes**
Changes introduced in this pull request:
- fix daily snapshot convoluted and bloated logs

**Reference issue to close (if applicable)**

Closes #321

**Other information and links**

### CODE REVIEW

File: terraform/modules/daily_snapshot/service/daily_snapshot.rb [hunk 1]
```diff
@@ -66,3 +66,6 @@ def latest_snapshot_date(chain_name = 'calibnet')
 [LOG_EXPORT_SCRIPT_RUN, LOG_EXPORT_DAEMON, LOG_EXPORT_METRICS].each do |log_file|
   puts "Snapshot export log:\n#{File.read(log_file)}\n\n" if File.exist?(log_file)
 end
+
+# Clean up daemon logs after everything is done
+File.delete(LOG_EXPORT_DAEMON) if File.exist?(LOG_EXPORT_DAEMON)
```
Comment (LesnyRumcajs) [inline terraform/modules/daily_snapshot/service/daily_snapshot.rb:71]: Why?

**Comment by LesnyRumcajs** [comment]
> > @samuelarogbonlo please attach a sample log file for review.
> 
> @LesnyRumcajs [calibnet_2023-11-07T14:25:26_script_run.txt](https://github.com/ChainSafe/forest-iac/files/13281604/calibnet_2023-11-07T14.25.26_script_run.txt)

What about metrics log?

File: terraform/modules/daily_snapshot/service/daily_snapshot.rb (hunk 1 above)
Comment (LesnyRumcajs) [reply terraform/modules/daily_snapshot/service/daily_snapshot.rb:71]: No. I mean't the logs themselves, as in removal of lines that are useless/redundant/noise. The file should stay.

**Review by LesnyRumcajs — APPROVED** [review]

**Review by lemmih — APPROVED** [review]
